### ISSUE TITLE
null pointer being thrown in no.steras.opensamlbook.OpenSAMLUtils.buildSAMLObject(Class<T>)

### ISSUE THREAD

**Issue by scanlonjts** [rasmusson/webprofile-ref-project#1]
Sample code:
                String responseStr = "largeB64EndodedStrhere";
                    Base64 decoder = new Base64();
                    byte[] thebytes = decoder.decode(responseStr);
                    logger.info(new String(thebytes));
                    Artifact artifact = OpenSAMLUtils.buildSAMLObject(Artifact.class);

Exception in thread "main" java.lang.NullPointerException
    at no.steras.opensamlbook.OpenSAMLUtils.buildSAMLObject(OpenSAMLUtils.java:48)
    at no.steras.opensamlbook.sp.ConsumerServlet.main(ConsumerServlet.java:262)

btw: I bought your book!  Very well put written and helpful!

**Comment by kasi1323** [comment]
I have signed Base64 encoded SAML Response, how can i extract attributes in this approach?
Recently i had gone through your book OpenSAML v3 . Unfortunately I did not find anywhere how to extract attributes if Protocol binding is HTTP POST. can anyone direct me?
